baseURL = 'https://firsttimeprogramming.github.io/my_hugo_paper_blog/'
languageCode = 'en-us'
title = 'my personal blog'
theme = 'paper'

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # add disqus comments

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # header social icons
  #twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
  github = 'firsttimeprogramming'       # github.com/YOUR_GITHUB_ID
  #instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'studyenglishonly@gmail.com'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'Ben'
  bio = 'secret'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon